language: node_js
node_js:
  - "11.8"
  - "10.15"
  - "9.11"
  - "8.15"
  - "7.10"
sudo: required
services: 
  - docker

before_install: 
  - 'nvm install-latest-npm'
  - docker build -t hmqiwt/docker-react -f Dockerfile.dev .

script: 
  - docker run hmqiwt/docker-react npm run test -- --coverage
allow_failures:
  - os: osx
  - env: TEST=true ALLOW_FAILURE=true
  - env: COVERAGE=true
  - env: POSTTEST=true
