language: node_js
node_js:
  - "10.15"
sudo: required
services: 
  - docker

before_install: 
  - docker build -t hmqiwt/docker-react -f Dockerfile.dev .

script: 
  - docker run hmqiwt/docker-react npm run test -- --coverage

