language: node_js
sudo: required
services: 
  - docker

before_install: 
  - docker build -t hmqiwtCode/docker-react -f Dockerfile.dev .

script: 
  - docker run hmqiwtCode/docker-react npm run test -- --coverage
